[package]
name = "binary_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
druid = "0.7.0"
tokio = { version = "1", features = ["full"] }
async-recursion = "1.0.0"